### ISSUE TITLE
Implement ability of OpenStack services to use redis as their oslo caching backend

### ISSUE THREAD

**Issue by fdobrovolny** [SovereignCloudStack/issues#489]
Epic #462 

Blocks #464 

As an SCS Operator, I want to use Ansible Kolla to deploy OpenStack Services with Redis backend for the future possibility of E2E encryption of OpenStack services.

## Definition of Ready:

- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:
- [x] Ansible Kolla can deploy OpenStack services with Redis as a caching backend.
- [ ] The patch has been submitted to upstream and merged.
- [ ] Change has been included in the testbed.
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by MatusJenca2** [comment]
# Issue Progress
## Openstack services using [oslo.cache](https://github.com/openstack/oslo.cache)
- Services that utilize `oslo.cache` library already support Redis (without TLS) as backend
- Add this option to kolla ansible, here's a [kolla fork](https://github.com/SovereignCloudStack/kolla-ansible) that has it
- After review of [PR in forked repo](https://github.com/SovereignCloudStack/kolla-ansible/pull/1/commits/b1775c1e09d00c0e6bd2910e407d86f246cc9d1a) by @fdobrovolny it a PR can be created in upstream

## Horizon 
- Horizon uses [Django](https://www.djangoproject.com/) and it's caching abilities
- Version of Django that Horizon uses does not support support redis cache, unless an additional library [django_redis](https://github.com/jazzband/django-redis) is installed
- This would require changes in the Docker images Kolla uses, I suggest we make it a sepparate issue
- Can be temporarily "hacked" by using `docker exec`
```yaml
# Add to ansible/roles/horizon/tasks/bootstrap.yml
- name: Install additional library to Horizon for Redis Cache
  community.docker.docker_container_exec:
    container: horizon
    command:  bash -c "source /var/lib/kolla/venv/bin/activate; pip install django_redis"
  become: yes 
```
## Keystone_auth

- [Keystone middleware](https://docs.openstack.org/keystonemiddleware/latest/middlewarearchitecture.html) cannot use Redis as caching backend, options are :
    - Memcached - we probably don't want to use that because of no TLS
    - Openstack Swift - is an Openstack Service, most probably has TLS as other OS services.
- I suggest we make this a sepparate issue, because it's  using Swift, not Redis
- Openstack seems to be working with Memacached disabled (Redis is used also for Horizon). This is however a single project on the single node, not sure if it works properly on real OS deployments. Also, we probably want users to be able to use caching feature for keystone_auth
