### ISSUE TITLE
Ensure security hardening of the KaaS monitoring solution - inner cluster communication

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/issues#495]
As a CSP, I require a secure KaaS cluster monitoring solution I offer

Explore the [k8s-observability](https://github.com/SovereignCloudStack/k8s-observability) repository and identify the TODOs that highlight instances where an insecure (HTTP) connection is used for the KaaS monitoring solution to collect metrics from Kubernetes control plane components (kube-controller-manager, etcd, kube-proxy, scheduler, etc.)

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by matofeder** [comment]
related: https://github.com/SovereignCloudStack/k8s-observability/issues/32

**Comment by matofeder** [comment]
See the following GitHub comment on how to secure connections between Kubernetes control plane components (kube-controller-manager, kube-scheduler, kube-proxy, etcd) and Prometheus Server: https://github.com/prometheus-community/helm-charts/issues/204#issuecomment-788065305

**Comment by matofeder** [comment]
###  kube-controller-manager, kube-scheduler

After a deeper investigation, it seems that the Prometheus server running in the worker node can not fully securely access the kube-controller-manager and kube-scheduler metrics endpoints (without some workaround), read an explanation [here](https://github.com/kubernetes/kubeadm/issues/2244). 

- Both kube-scheduler and kube-controller-manager have 127.0.0.1 as DN in TLS certificate. So scraping from a non-master host is only possible with insecureSkipVerify: true
- By default, both components bind to 127.0.0.1. Binding with extraArgs: {bind-address: "0.0.0.0"} works, but exposes the components too broadly: cluster-wide and probably even outside the cluster, depending on bound interfaces.

Two approaches are discussed to workaround the above issues:
- Delegate scraping to some collector, ran as a DaemonSet. E.g. HA proxy can act as such. It may pass proxy request to the node and respond to Prometheus with the result, see https://github.com/prometheus-operator/kube-prometheus/issues/913#issuecomment-1065494045
- Create custom certificates, mount them to the kube-scheduler and kube-controller-manager containers, and instruct them to use these certificates, e.g. see https://github.com/kubernetes/kubernetes/issues/80063#issuecomment-510909021

### etcd

Etcd DB can expose metrics via HTTPS. The metrics endpoint should be configured as follows `--listen-metrics-urls=https://0.0.0.0:PORT`.
Then the client (i.e. Prometheus) should shrape the metrics endpoint with a valid client certificate, see https://github.com/prometheus-community/helm-charts/issues/204#issuecomment-765155883

### kube-apiserver

kube-prometheus-stack creates a token and mounts k8s/PKI dir to the prometheus container. Prometheus uses them, so the connection from prometheus to the Kubernetes API metrics endpoint is **already secure**. 
See the Prometheus config using the default kube-prometheus-stack deployment:
```yaml
- job_name: serviceMonitor/default/kube-prometheus-apiserver/0
  metrics_path: /metrics
  scheme: https
  authorization:
    type: Bearer
    credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    server_name: kubernetes
    insecure_skip_verify: false
```

### kube-proxy

It seems that kube-proxy does not support TLS, hence secure communication with its metrics endpoint is not possible (directly), see https://github.com/kubernetes/kubernetes/issues/106870

As a possible workaround the [ztunnel](https://istio.io/latest/docs/ops/ambient/usage/ztunnel/) is recommended.

### kubelet

- By default the kubelet serving certificate deployed by kubeadm is **self-signed**. This means a connection from external services like the [metrics-server](https://github.com/kubernetes-sigs/metrics-server)/kube-api or Prometheus to a kubelet cannot be secured with TLS, see the [docs](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#kubelet-serving-certs)
- Hence the kube-promtheus-stack [skips the TLS verification](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml#L38) as well as others (metrics-server (--kubelet-insecure-tls), [kubeapi](https://kubernetes.io/docs/concepts/architecture/control-plane-node-communication/#api-server-to-kubelet)) 

The above could be resolved as follows:
- kubelet could obtain properly signed serving certificates (signed by the Kubernetes CA) via the `serverTLSBootstrap: true` field. This enables the bootstrap of kubelet server certificates by requesting them from the `certificates.k8s.io` API
- One known limitation is that the CSRs (Certificate Signing Requests) for these certificates cannot be automatically approved by the default signer in the kube-controller-manager - [kubernetes.io/kubelet-serving](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers). This will require action from the user or a third party controller (e.g. [kubelet-csr-approver ](https://github.com/postfinance/kubelet-csr-approver))
- Then the kube-Prometheus-stack should be adjusted to not skip the TLS verification. The rest needed for TLS communication is already covered by the kube-promtheus-stack servicemonitor settings when the `https` is used:
```yaml
- job_name: serviceMonitor/default/kube-prometheus-kubelet/0
  metrics_path: /metrics
  scheme: https
  authorization:
    type: Bearer
    credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
```

The above scenario has been successfully tested using kind:
- Set `serverTLSBootstrap: true` in KubeletConfiguration, see e.g. [this tutorial](https://www.zeng.dev/post/2023-kubeadm-enable-kubelet-serving-certs/#ideal-solution)
- Deploy kube-prometheus-stack
- Adjust kubelet service monitor and set `insecureSkipVerify: false`
- Prometheus scrapes kubelet metrics endpoints via TLS
