### ISSUE TITLE
Configure ExternalDNS on the shared cluster to get use of `k8s.scs.community`

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/issues#553]

**Comment by jschoone** [comment]
Installed with Helm:
```
helm repo add external-dns https://kubernetes-sigs.github.io/external-dns
helm repo update
helm upgrade -i external-dns external-dns/external-dns --version 1.14.3 --values values.yaml --namespace external-dns --create-namespace
```

values.yaml:
```yaml
env:
  - name: OS_AUTH_URL
    value: https://api.dc1.muc.cloud.cnds.io:5000/v3 # artcodix DNS
  - name: OS_REGION_NAME
    value: MUC
  - name: OS_APPLICATION_CREDENTIAL_ID
    value: <application_credential_id>
  - name: OS_APPLICATION_CREDENTIAL_SECRET
    value: "<application_credential_secret"
provider:
  name: designate
sources:
  - service
  - ingress
policy: sync
```
