### ISSUE TITLE
Setup example customer domain/realm for federation

### ISSUE THREAD

**Issue by reqa** [SovereignCloudStack/issues#596]
As a SCS Operator, I want to see an example of how to setup Keycloak and Keystone mapping so that a new customer domain/realm can onboard it's federated users.

## Acceptance Criteria:
- [ ] Documentation
- [ ] Adjust testbed deployment to actually create an example customer realm and home-idp-discovery in Keycloak

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by JuanPTM** [comment]
I got some notes about what should we make:

- [x] Create Proxy realm (`OSISM` in the testbed)
- [x] Client for `keystone` in `OSISM` realm
- [x] Create Customer Realm (`Customer` in the testbed)
- [x] Creating the client on the `Customer` realm (and mappers)
    - [x] Create Mappers for client 
- [x] Creating the federation on the `OSISM` realm (and mappers)
    - [x] Create Mappers for federation
- [x] Create a new login flow that uses the IdP discovery plugin
   - [ ]  Set `ALTERNATIVE` requirement on the login flow steps
- [x] Configure the home IdP Discovery plugin
- [x] Create `Alice` user in `Customer` realm

I think I didn't forget anything.

**Comment by JuanPTM** [comment]
MR created, still in draft status until we figure out how to modify the requirements status of the steps in the login flow.

https://github.com/osism/ansible-playbooks/pull/403

**Comment by JuanPTM** [comment]
Added an initial version to the docs. https://github.com/SovereignCloudStack/docs/pull/190

**Comment by JuanPTM** [comment]
Currently there is a small problem to finish the ansible-playbook:
To change the requirement status of a step inside a login flow, the keycloak CLI tool needs a json file. I've tried to create the file inside the keycloak pod to use it on the next step to modify each step, but I've failed.

Here is a snippet of what I've tried. The main idea is to create the json file and then use it on the next call.

```
# TODO: Fix subflow ALTERNATIVE status
    - name: JSONs ALTERNATIVE status
      copy: >-
        kubectl exec -n {{ keycloak_namespace }} {{ keycloak_service_container_name }} --
          cat "{\"id\":\"{{ item }}\",\"requirement\":\"ALTERNATIVE\"}" >> "{{ item }}.json"
      environment:
        KUBECONFIG: /share/kubeconfig
      loop: "{{ available_executions_json.stdout | from_json | map(attribute='id') | list }}"
      run_once: true
      no_log: false
      changed_when: true

# TODO: Fix subflow ALTERNATIVE status
    - name: Update subflow ALTERNATIVE status
      ansible.builtin.command: >-
        kubectl exec -n {{ keycloak_namespace }} {{ keycloak_service_container_name }} --
          {{ keycloak_kcadm_binary }}
          update authentication/flows/{{ idp_login_flow }}/executions
            --target-realm "{{ keycloak_proxy_realm }}"
            -f "{{ item }}.json"
      environment:
        KUBECONFIG: /share/kubeconfig
      loop: "{{ available_executions_json.stdout | from_json | map(attribute='id') | list }}"
      run_once: true
      no_log: false
      changed_when: true
```

**Comment by JuanPTM** [comment]
> Currently there is a small problem to finish the ansible-playbook: To change the requirement status of a step inside a login flow, the keycloak CLI tool needs a json file. I've tried to create the file inside the keycloak pod to use it on the next step to modify each step, but I've failed.
> 
> Here is a snippet of what I've tried. The main idea is to create the json file and then use it on the next call.
> 
> ```
> # TODO: Fix subflow ALTERNATIVE status
>     - name: JSONs ALTERNATIVE status
>       copy: >-
>         kubectl exec -n {{ keycloak_namespace }} {{ keycloak_service_container_name }} --
>           cat "{\"id\":\"{{ item }}\",\"requirement\":\"ALTERNATIVE\"}" >> "{{ item }}.json"
>       environment:
>         KUBECONFIG: /share/kubeconfig
>       loop: "{{ available_executions_json.stdout | from_json | map(attribute='id') | list }}"
>       run_once: true
>       no_log: false
>       changed_when: true
> 
> # TODO: Fix subflow ALTERNATIVE status
>     - name: Update subflow ALTERNATIVE status
>       ansible.builtin.command: >-
>         kubectl exec -n {{ keycloak_namespace }} {{ keycloak_service_container_name }} --
>           {{ keycloak_kcadm_binary }}
>           update authentication/flows/{{ idp_login_flow }}/executions
>             --target-realm "{{ keycloak_proxy_realm }}"
>             -f "{{ item }}.json"
>       environment:
>         KUBECONFIG: /share/kubeconfig
>       loop: "{{ available_executions_json.stdout | from_json | map(attribute='id') | list }}"
>       run_once: true
>       no_log: false
>       changed_when: true
> ```

My current approach is to create the files, create a task that does the kubectl cp into the kc pod and finally run the kcadmin command

**Comment by berendt** [comment]
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html

You have to do it this way:

```
- name: Copy using inline content
  ansible.builtin.copy:
    content: '# This file was moved to /etc/other.conf'
    dest: "{{ item }}.json
```

You try to use a shell command. If you want to do it this way (ansible.builtin.copy is better) you have to use the ansible.builtin.shell task.

**Comment by JuanPTM** [comment]
> https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
> 
> You have to do it this way:
> 
> ```
> - name: Copy using inline content
>   ansible.builtin.copy:
>     content: '# This file was moved to /etc/other.conf'
>     dest: "{{ item }}.json
> ```
> 
> You try to use a shell command. If you want to do it this way (ansible.builtin.copy is better) you have to use the ansible.builtin.shell task.

I've tried that but the file created ends up on the osism-ansible container, then I try to `kubectl cp` it into the keycloak pod, but it doesn't work 

```
# TODO: Fix subflow ALTERNATIVE status
    - name: Create JSONs ALTERNATIVE status
      ansible.builtin.copy:
        dest: "/tmp/{{ item }}.json"
        content: '{"id": {{ item }},"requirement":"ALTERNATIVE"}'
      with_items: "{{ available_executions_json.stdout | from_json | map(attribute='id') | list }}"
      run_once: true
      no_log: false
      changed_when: true

    - name: Copy JSONs ALTERNATIVE status into KC
      ansible.builtin.command: >-
        kubectl cp /tmp/{{ item }}.json
        {{ keycloak_namespace }}/{{ keycloak_service_container_name }}:/tmp/{{ item }}.json
      environment:
        KUBECONFIG: /share/kubeconfig
      loop: "{{ available_executions_json.stdout | from_json | map(attribute='id') | list }}"
      run_once: true
      no_log: false
      changed_when: true


# TODO: Fix subflow ALTERNATIVE status
    - name: Update subflow ALTERNATIVE status
      ansible.builtin.command: >-
        kubectl exec -n {{ keycloak_namespace }} {{ keycloak_service_container_name }} --
          {{ keycloak_kcadm_binary }}
          update authentication/flows/{{ idp_login_flow }}/executions
            --target-realm "{{ keycloak_proxy_realm }}"
            -f "/tmp/{{ item }}.json"
      environment:
        KUBECONFIG: /share/kubeconfig
      loop: "{{ available_executions_json.stdout | from_json | map(attribute='id') | list }}"
      run_once: true
      no_log: false
      changed_when: true

```

Currently I have the files correctly created on `/tmp/{id}.json`
