### ISSUE TITLE
Test the up-to-date version of SONiC community image on the SCS Landscape network infrastructure

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/issues#706]
According to the following documents 
- https://input.scs.community/HlTFVjFIS3umxZcSLOcZsQ#
- https://input.scs.community/SCS-DR-SONIC-usage#

the SONiC community image in version SONiC-OS-202305.0-dirty-20231102.180401 failed to show system-health summary (
tested on Accton-AS7326-56X a.k.a Edgecore 7326-56X-O-AC-B):
```
$ sudo show system-health summary 
chassis.set_status_led is not implemented
...
AttributeError: 'Chassis' object has no attribute 'initizalize_system_led'
```

This issue aims to test whether the most recent SONiC community build failed too.

**Comment by matofeder** [comment]
Test with the most recent build of the SONiC community image for the Broadcom platform: sonic-broadcom-202405-619116
unfortunately failed on the same error. 

```
$ show version 

SONiC Software Version: SONiC.202405.619116-dad1a1d90
SONiC OS Version: 12
Distribution: Debian 12.5
Kernel: 6.1.0-11-2-amd64
Build commit: dad1a1d90
Build date: Wed Aug 14 13:26:30 UTC 2024
Built by: azureuser@4a514b7ac000006

Platform: x86_64-accton_as7326_56x-r0
HwSKU: Accton-AS7326-56X
ASIC: broadcom
ASIC Count: 1
Serial Number: 732656X2317026
Model Number: FP4ZZ7656009A
Hardware Revision: N/A
Uptime: 08:49:55 up 18:01,  1 user,  load average: 0.64, 0.69, 0.74
Date: Thu 15 Aug 2024 08:49:55
```

```
sudo show system-health summary
chassis.set_status_led is not implemented
Traceback (most recent call last):
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/show/system_health.py", line 113, in summary
    _, chassis, stat = get_system_health_status()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/show/system_health.py", line 32, in get_system_health_status
    chassis.initizalize_system_led()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Chassis' object has no attribute 'initizalize_system_led'
```

Therefore it seems, that the issue has not been addressed yet upstream. 
IMO It is not crucial from the main functionality of SONiC OS point of view, but indeed sub-optimal. 

Upstream contains some nice example on another platform on how to fix the issue: [DellEMC: S5232F support for show system-health command](https://github.com/sonic-net/sonic-buildimage/issues/8261)

In addition, the VP04 team resolved the issue on Accton-AS7326-56X with this patch https://github.com/SovereignCloudStack/sonic-buildimage/pull/1 

Therefore, it would be great to cleanup the above PR and publish it upstream.

**Comment by matofeder** [comment]
It seems that the latest master branch of SONiC works better, therefore I re-opened this issue and will investigate how the latest master works with Accton devices of SCS.

**Comment by matofeder** [comment]
- Test with SONiC community - version SONiC.master.645186-367495d03
  - sw1g - works!, it reports not running containers which is true
    - platform: x86_64-accton_as4630_54te-r0
    ```
    # show system-health summary 
    System status summary
    
      System status LED  STATUS_LED_COLOR_GREEN
      Services:
        Status: Not OK
        Not Running: swss, syncd:syncd
      Hardware:
        Status: OK
    ```
  - sw10g - works, **but** it reports Not OK Hardware Status. It seems that some HW definitions for this device are still missing.
    - platform: x86_64-accton_as5835_54x-r0
    ```
    # show system-health summary
    System status summary
    
      System status LED  STATUS_LED_COLOR_GREEN
      Services:
        Status: Not OK
        Not Running: monit
      Hardware:
        Status: Not OK
        Reasons: PSU 2 is missing or not available
                 PSU 1 is missing or not available
                 PSU-2 FAN-1 is missing
                 PSU-1 FAN-1 is missing
                 FAN-5R is missing
                 FAN-5F is missing
                 FAN-4R is missing
                 FAN-4F is missing
                 FAN-3R is missing
                 FAN-3F is missing
                 FAN-2R is missing
                 FAN-2F is missing
                 FAN-1R is missing
                 FAN-1F is missing
    ```
    - It seems that the patch is available upstream (since 2023), but has not merged yet, see https://github.com/sonic-net/sonic-buildimage/pull/13700
  - sw25g - the [error](https://github.com/SovereignCloudStack/issues/issues/706#issuecomment-2290912934) still persists
    - platform: x86_64-accton_as7326_56x-r0
    ```
    # show system-health summary
    chassis.set_status_led is not implemented
   ...
    AttributeError: 'Chassis' object has no attribute 'initizalize_system_led
    ```
  - sw100g - does not work, but does not fail, the health configuration file is missing
    - platform: x86_64-accton_as7726_32x-r0
    ```
    # show system-health summary 
    System health configuration file not found, exit...
    ```
    - It seems that the patch is available upstream (since 2022), but has not merged yet, see https://github.com/sonic-net/sonic-buildimage/pull/12993
    
    
--- 

Overall the latest `master` branch version works better than the latest stable version `202405` of  SONiC community. 
It seems that the patches are available but the community SONiC merging process is too slow (more than 800 open PRs).

It seems that the EdgeCore enterprise SONiC contains commits like this https://github.com/edge-core/sonic-buildimage/commit/4be14f0ac451d5d7e208e374376ddd7ae935a551, where the EdgeCore enterprise SONiC ports lot of open patches from the community version of SONiC.

**Comment by matofeder** [comment]
The next step could be to build our own SCS SONiC community image with the following patches/features:
- Enable ZTP (in community builds ZTP is not enabled by default) 
-  Integrated mode with sonic-frr-mgmt-framework (frrcfgd) related issues (described in detail [here](https://github.com/SovereignCloudStack/hardware-landscape/blob/main/documentation/sonic/FRR.md#which-frr-configuration-options-are-not-supported-in-the-integrated-mode-with-sonic-frr-mgmt-framework-frrcfgd-and-does-this-affect-scs-landscape-configuration)):
    - Support configuring source IP/IPv6 for routes https://github.com/sonic-net/sonic-buildimage/pull/20333
    - Fixes that edge-core ported from community repo https://github.com/edge-core/sonic-buildimage/commit/4be14f0ac451d5d7e208e374376ddd7ae935a551
        - Patch contains not only FRR related issues but also another fixes for, as7326-56x, as7726-32x, as5835-54x, as4625-54t
  - Fix for https://github.com/sonic-net/sonic-buildimage/issues/19930 - ! Not addressed yet!  It needs to be done upstream. @matofeder is on it
    - EDIT: FIX available https://github.com/sonic-net/sonic-utilities/pull/3565

**Comment by matofeder** [comment]
- Test with SONiC community - version SONiC.fix_edgecore.0-dirty-20241004.143208 build with branch https://github.com/SovereignCloudStack/sonic-buildimage/pull/4 (see PR description for details) 

  - sw1g - works
    - Issues:
       -  System-health reports Not OK Hardware Status and an issue with SW fans, It has to be investigated whether the problem is there (a new issue that comes with this build)
          - It seems that some extended support for the YM-1151D PSU patch already exists upstream, but it has not been merged yet: https://github.com/sonic-net/sonic-buildimage/pull/8638 (the edge core already contains this patch). It needs to be tested to see whether the patch resolves the fan direction issue. 
       - It reports not running containers, which is true, but it needs to be investigated why swss and syncd are in a non-healthy state. 
         - Syslog entry `ERR syncd#syncd: :- loadProfileMap: failed to open profile map file: /usr/share/sonic/hwsku/sai.profile: No such file or directory` indicates that `syncd` did not find `sai.profile` file for platform as4630_54te. Two upstream PRs want to add this and related files for the affected platform: https://github.com/sonic-net/sonic-buildimage/pull/6949 and https://github.com/sonic-net/sonic-buildimage/pull/11805. The second one seems to be more recent and in addition, adds dynamic port breakout support (it is also ported in the edge-core distro)
    - platform: x86_64-accton_as4630_54te-r0
    ```
    # show system-health summary
    System status summary
    
      System status LED  STATUS_LED_COLOR_GREEN
      Services:
        Status: Not OK
        Not Running: swss, syncd:syncd
      Hardware:
        Status: Not OK
        Reasons: PSU-2 FAN-1 direction exhaust is not aligned with FAN-1 direction intake
                 PSU-1 FAN-1 direction exhaust is not aligned with FAN-1 direction intake

    ```
  - sw10g - works
    - Issues:
       -  System-health reports Not OK Hardware Status and an issue with SW fans. 
          - It seems that the fan direction of YM-1401A-CR PSU is wrong and edgecore fixed this in its enterprise distribution https://github.com/edge-core/sonic-buildimage/pull/198 (fix could be ported upstream)
    - platform: x86_64-accton_as5835_54x-r0
    ```
    # show system-health summary
    System status summary
    
      System status LED  amber
      Services:
        Status: OK
      Hardware:
        Status: Not OK
        Reasons: PSU-2 FAN-1 direction exhaust is not aligned with FAN-1F direction intake
                 PSU-1 FAN-1 direction exhaust is not aligned with FAN-1F direction intake
    ```
  - sw25g - works without issues
    - platform: x86_64-accton_as7326_56x-r0
    ```
    # show system-health summary                                                                                                                                                             
    System status summary                                                                                                                                                                                            
      System status LED  green                                                                                                                                                                                        
      Services:                                                                                                                                                                                                       
        Status: OK                                                                                                                                                                                                    
      Hardware:                                                                                                                                                                                                       
        Status: OK  
    ```
  - sw100g - works without issues
    - platform: x86_64-accton_as7726_32x-r0
    ```
    # show system-health summary 
    System status summary
    
      System status LED  green
      Services:
        Status: OK
      Hardware:
        Status: OK
    ```

--- 

Overall fixed SCS SONiC image (based on the latest community master version) works much better than the vanilla latest community master version of SONiC. 
Some issues still occur for 1g and 10g SWs, but again, it seems that patches are already upstream but have not been merged yet :/. 
The next step is to port the above PRs into the SCS SONiC build branch https://github.com/SovereignCloudStack/sonic-buildimage/pull/4 and test it.

**Comment by matofeder** [comment]
- Test with SONiC community - version **sonic-fix_edgecore.0-10b4356bf.bin** build with branch https://github.com/SovereignCloudStack/sonic-buildimage/pull/4 (see PR description for details) 

  - sw1g - works with minor issue
    - Issues:
       -  System-health reports Not OK Hardware Status and an issue with SW fans, It has to be investigated whether the problem is there (a new issue that comes with this build)
          - It seems that some extended support for the YM-1151D PSU patch already exists upstream, but it has not fix the above issue, I put the comment there and we will see whether is something missing in the mentioned PR or not, https://github.com/sonic-net/sonic-buildimage/pull/8638#issuecomment-2404447274
          - Overall, this issue is not considered blocking
         
    - platform: x86_64-accton_as4630_54te-r0
    ```
    # show system-health summary
    System status summary
    
      System status LED  STATUS_LED_COLOR_AMBER
      Services:
        Status: OK
      Hardware:
        Status: Not OK
        Reasons: PSU-2 FAN-1 direction exhaust is not aligned with FAN-1 direction intake
                 PSU-1 FAN-1 direction exhaust is not aligned with FAN-1 direction intake
    ```
  - sw10g - works without issues
    - platform: x86_64-accton_as5835_54x-r0
    ```
    # show system-health summary
    System status summary
    
      System status LED  green
      Services:
        Status: OK
      Hardware:
        Status: OK
    ```
  - sw25g - works without issues
    - platform: x86_64-accton_as7326_56x-r0
    ```
    # show system-health summary                                                                                                                                                             
    System status summary                                                                                                                                                                                            
      System status LED  green                                                                                                                                                                                        
      Services:                                                                                                                                                                                                       
        Status: OK                                                                                                                                                                                                    
      Hardware:                                                                                                                                                                                                       
        Status: OK  
    ```
  - sw100g - works without issues
    - platform: x86_64-accton_as7726_32x-r0
    ```
    # show system-health summary 
    System status summary
    
      System status LED  green
      Services:
        Status: OK
      Hardware:
        Status: OK
    ```

--- 

Overall fixed SCS SONiC image (based on the latest community master version) works better than the vanilla latest community master version of SONiC. 
One issue (system-health monitor related) still occurs for 1g SW, but it is not considered blocking.
