### ISSUE TITLE
[Cluster Stacks] Automate creation of Cluster Stack release assets using Zuul 

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/issues#727]
Things to automate

- [ ] Create assets using `csctl`
- [ ] Push assets to Harbor using `csctl`
- [ ] Define management cluster (e.g. moin-cluster)
- [ ] Deploy Cluster Stack resource
- [ ] Build cluster based on new Cluster Class
- [ ] Track https://github.com/osism/k8s-capi-images/ for new images

**Comment by jschoone** [comment]
# Notes about all the stuff

Requirements:
- git
- go
- make
- PyYAML
- helm

## Build and publish Cluster Stacks

Basic workflow to create assets from Cluster Stack defintion
```bash
git clone https://github.com/SovereignCloudStack/cluster-stacks
git clone https://github.com/SovereignCloudStack/csctl
git clone https://github.com/SovereignCloudStack/csctl-plugin-openstack
cd csctl
make build
cp csctl /usr/local/bin
cd ../csctl-plugin-openstack
make build
cp csctl-openstack /usr/local/bin
cd ../cluster-stacks
./hack/generate_version.py --build # works only for Cluster Stack openstack-scs
csctl create -m hash providers/openstack/out/1-29/ # useless in ci because assets are only available locally
```

Needed secrets:
OCI_REGISTRY
OCI_REPOSITORY
OCI_USERNAME
OCI_PASSWORD
or
OCI_ACCESS_TOKEN 

KUBECONFIG 

Workflow to push assets to OCI registry
```
# export OCI_ variables
cd cluster-stacks
csctl create -m hash --publish --remote oci providers/openstack/out/1-29/
```
in our example we got version openstack-scs-1-29-v0-sha-ihtybxi
which is available in .releases and in the $OCI_REPOSITORY


Thoughts:
When generating cluster stacks with `generate_version.py`, versions should always be in `providers/openstack/scs`
Example for 1.29:
1. generate versions
2. replace generated folder `providers/openstack/scs` with `providers/openstack/out/1-29`
3. push to branch `chore/update-1.29`
4. create PR against `release-1.29`

## Automatically check for new versions
We depend on various versions
- kubernetes from https://github.com/osism/k8s-capi-images/
- occm and cinder-csi from https://github.com/kubernetes/cloud-provider-openstack/tree/master/charts
  - openstack-cloud-controller charts have versions depending on kubernetes version. For example for kubernetes 1.29.x it is occm Helm chart version 2.29.x (see https://github.com/kubernetes/cloud-provider-openstack/blob/release-1.29/charts/openstack-cloud-controller-manager/Chart.yaml)

## Test in Cluster (probably out of scope here)

Results in Cluster Stack object:
```
apiVersion: clusterstack.x-k8s.io/v1alpha1
kind: ClusterStack
metadata:
  name: openstack-scs-129
spec:
  autoSubscribe: false
  channel: stable
  kubernetesVersion: "1.29"
  name: scs
  noProvider: false
  provider: openstack
  providerRef:
    apiVersion: infrastructure.clusterstack.x-k8s.io/v1alpha1
    kind: OpenStackClusterStackReleaseTemplate
    name: cspotemplate
  versions:
    - v0-sha.ihtybxi
```
```
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cs-cluster
  labels:
    managed-secret: cloud-config
spec:
  topology:
    class: openstack-scs-1-29-v0-sha.ihtybxi
    controlPlane:
      replicas: 1
    version: v1.29.10
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: 1
```
